nodeLinker: node-modules
enableGlobalCache: true

yarnPath: .yarn/releases/yarn-4.5.3.cjs

packageExtensions:
  eslint-config-next@*:
    peerDependencies:
      typescript: '*'
      '@typescript-eslint/parser': '*'
      '@typescript-eslint/eslint-plugin': '*'

supportedArchitectures:
  os: [darwin]
  cpu: [arm64]

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard

npmRegistryServer: 'https://registry.yarnpkg.com'

preferInteractive: true

enableHyperlinks: true
