enableGlobalCache: true
enableHyperlinks: true
enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard

nodeLinker: node-modules

npmRegistryServer: 'https://registry.yarnpkg.com'

packageExtensions:
  next@*:
    dependencies:
      react: '>=18.0.0'
      react-dom: '>=18.0.0'
  eslint-config-next@*:
    peerDependencies:
      '@typescript-eslint/eslint-plugin': '*'
      '@typescript-eslint/parser': '*'
      typescript: '*'

preferInteractive: true

supportedArchitectures:
  cpu:
    - arm64
  os:
    - darwin

yarnPath: .yarn/releases/yarn-4.5.3.cjs
